### ISSUE TITLE
Publications incorrectes

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/acceslibre-schema#19]
Le [changelog](https://github.com/MTES-MCT/acceslibre-schema/blob/master/CHANGELOG.md) indique l'existence de versions 0.0.11 et 0.0.12 du schéma, malheureusement celles-ci n'ont pas été publiées correctement : il manque les tags Git pour ces versions.

Par ailleurs, la date de modification doit être mise à jour pour chacune de ces versions (champ `lastModified`), de même que l'URL de la version du schéma (`path`) et des fichiers d'exemple (`resources`). 

Plus d'informations ici : https://schema.data.gouv.fr/validation.html

**Comment by mlvernay** [comment]
Merci, c'est normalement corrigé avec la 0.0.14. 
Désolée pour le délai !
